export { default as Header } from '@/layout/mainHeader';
export { default as Hero } from './Hero';
export { default as TrustedBy } from './TrustedBy';
export { default as HowItWorks } from './HowItWorks';
export { default as Features } from './Features';
export { default as SampleCourses } from './SampleCourses';
export { default as Statistics } from './Statistics';
export { default as Testimonials } from './Testimonials';
export { default as FAQ } from './FAQ';
